version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    allow:
      - dependency-name: ruff
      - dependency-name: pytest
      - dependency-name: pytest-asyncio
